### ISSUE TITLE
Pre-trained CLIP model for Computing VT-CLIPScore

### ISSUE THREAD

**Issue by ShramanPramanick** [jylins/videoxum#2]
Hi Authors, 

Thanks for making the dataset and the codebase public. I want to compute the VT-CLIPScore metric, but I cannot find the weights of pre-trained CLIP on VideoXum. Will you please provide the pre-trained weights and the pre-training script? Without these, computing your proposed metric seems impossible.

Thanks,
Shraman

**Comment by jylins** [comment]
Thanks for your interest. The pre-trained CLIP on VideoXum is publicly available. Please refer to our Huggingface repo [[link](https://huggingface.co/jylins/vtsum_blip/blob/main/vt_clip.pth)].
