### ISSUE TITLE
Regarding vt_clip.pth Pretrained Model File

### ISSUE THREAD

**Issue by Amaan-Akhtar** [jylins/videoxum#3]
Hi,
I am currently exploring the project and would like to replicate the results. However, I couldn't locate the **vt_clip.pth** pretrained model file, which seems essential for the implementation.
Could you please provide a link to download the file or guidance on how to generate it?

**Comment by jylins** [comment]
Thanks for your interest. Please check this [link](https://huggingface.co/jylins/vtsum_blip/blob/main/vt_clip.pth).
